version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11

    working_directory: /go/src/github.com/cpanato/mattermost-plugin-aws-sns
    steps:
      - checkout

      - run: curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
      - run: make check-style
      - run: make test
